### ISSUE TITLE
V0.3.0/woorek IMDB Venice 영화제 수집 Dag에서 발생한 이슈입니다.

### ISSUE THREAD

**Issue by woorek** [oppenheimer-joa/airflow#12]
<img width="905" alt="image" src="https://github.com/oppenheimer-joa/airflow/assets/86358091/9bfee559-05af-43e6-b29e-0291004b3164">

Dag 이미지에서 확인할 수 있듯이 check_IMDB_venice 태스크가 초록불을 띄우지만

<img width="832" alt="image" src="https://github.com/oppenheimer-joa/airflow/assets/86358091/4a64c8a9-feae-4a00-bcb6-b0f3f5426a5f">

docker logs를 찍어봤을 때 이미지 마지막 라인에서 볼 수 있듯이 **422 Unprocessable Entity**를 띄웁니다.

@soobeen-byul @J3llyBe4n

**Comment by J3llyBe4n** [comment]
<img width="832" alt="image" src="https://github.com/oppenheimer-joa/airflow/assets/86358091/4a64c8a9-feae-4a00-bcb6-b0f3f5426a5f">


31번 째 줄(마지막) year = 에 '=' 이 빠졋습니다! 수정해주시면 될 것 같아요
