### ISSUE TITLE
[Error] Airflow AWS RDS DB 접속 에러

### ISSUE THREAD

**Issue by blahxblah** [oppenheimer-joa/airflow#21]
안녕하세요. 슬.문.생 팀 blahxblah 입니다.

지난주 토요일부터 Airflow 박스오피스 Dag에서 DB 접속 에러가 지속적으로 발생하고 있습니다.
단순히 박스오피스의 코드 부분이나 일시적인 오류일 것이라 생각했는데 오늘 Kopis의 Dag에서도 DB 접속오류가 발생하면서 AWS RDS나 코드 상의 DB 접속로직에 문제가 있지 않나 예상합니다.

- boxoffice dag 오류 log
```
mysql.connector.errors.DatabaseError: 1129: Host '172.31.4.247' is blocked because of many connection errors; unblock with 'mysqladmin flush-hosts'
```

- kopis dag 오류 log
```
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
During handling of the above exception, another exception occurred:

requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

- 해당 오류는 rds db에서 접속해서
```mysql
flush hosts;
```
명령어를 입력해서 호스트 초기화를 하면 해결이 됩니다만 일시적인 해결책으로 근본 원인을 찾아봐야 할 듯 합니다.

**Comment by J3llyBe4n** [comment]
해결 방안

해당 오류는 python module로 connection을 붙을때, 
max_connections와 max_connect_errors가 문제를 발생시키고 있는 것으로 보입니다.
python operator가 conn을 붙일때, 별다른 execute()나,  commit() 이 없다면, mysql 은 비정상적인 conn으로 판단하여, 해당 수를 ++ 합니다. 따라서, 해당 수가 설정값에 도달했을때, conn 자체가 불가하도록 설계되어있으며, 현재 에러가 발생하는 bulk 데이터 처리 + db_conn 숫자가 기하 급수적으로 늘어날때에는 해당 옵션을 넉넉하게 설정하여, 해당 에러는 회피 할 수 있도록 하면 됩니다.

```
# mysql 연결 최대 수 확인
select @@max_connections;

# max_connection 수 재 정의
set @@global max_connections=10000;

#mysql 연결 오류 수 확인
select @@max_connect_errors;

# 연결 오류 수 재정의
set @@global max_connect_errors=100000;

```

해당 오류는
